// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfAJAEs37-UFNKC9clUDBcJRq_4ZDlk3s',
    appId: '1:797232554715:web:203f776fd4c7f190efa2fe',
    messagingSenderId: '797232554715',
    projectId: 'belal-bb02f',
    authDomain: 'belal-bb02f.firebaseapp.com',
    storageBucket: 'belal-bb02f.appspot.com',
    measurementId: 'G-6TDH9HDM68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-UE-rC2eAcD6AqtVELmIgMGJ1-gVnARg',
    appId: '1:797232554715:android:b30a9af6e92435e7efa2fe',
    messagingSenderId: '797232554715',
    projectId: 'belal-bb02f',
    storageBucket: 'belal-bb02f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOAHKNY2WZZ-nJsxA9MHzsnvjiWkZeG0U',
    appId: '1:797232554715:ios:e0b5b262fbc120a0efa2fe',
    messagingSenderId: '797232554715',
    projectId: 'belal-bb02f',
    storageBucket: 'belal-bb02f.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOAHKNY2WZZ-nJsxA9MHzsnvjiWkZeG0U',
    appId: '1:797232554715:ios:e0b5b262fbc120a0efa2fe',
    messagingSenderId: '797232554715',
    projectId: 'belal-bb02f',
    storageBucket: 'belal-bb02f.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfAJAEs37-UFNKC9clUDBcJRq_4ZDlk3s',
    appId: '1:797232554715:web:419aba020f21fd71efa2fe',
    messagingSenderId: '797232554715',
    projectId: 'belal-bb02f',
    authDomain: 'belal-bb02f.firebaseapp.com',
    storageBucket: 'belal-bb02f.appspot.com',
    measurementId: 'G-3R7WGQ5JS9',
  );

}